name: Update Overleaf

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: Rscript install-packages.R

    - name: Generate plots
      run: Rscript generate-plots.R

    - name: Update Overleaf
      run: |
        # Use Overleaf API to update your project with new plots
        # Replace 'PROJECT_ID' and 'API_KEY' with your project ID and API key
        curl --request PUT --header "Authorization: Bearer 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" --data-binary "@update.zip" "https://www.overleaf.com/project/653700986d91b2026fa80f89"

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update Overleaf"
        git push
